### PR TITLE
Two fixes on recurring events

### PR DESCRIPTION
**Pull request by sixstone-qq**
* Fix exception modifications import in recurrence series
* Fix weekly recurring events exported to Outlook from SOGo

See the reasoning on the commit messages.

### CODE REVIEW

**Comment by blaxter** [comment]
@jenkins-zentyal if you like cats on roombas test this please

**Comment by blaxter** [comment]
:+1:

**Comment by sixstone-qq** [comment]
Test this please for the god's sake.

**Comment by blaxter** [comment]
test this please

**Comment by blaxter** [comment]
test this please :unamused:

**Comment by sixstone-qq** [comment]
test this please svp por favor...

**Pull request merged**
