### PR TITLE
 RTFHandler: Use specific loop for text actions 

### PR DESCRIPTION
**Pull request by javierag**
Normally the text sections will be longer that one character so
we can do a specific loop for this section.
This reduces the number of calls to [NSString dataUsingEncoding:]
and [NSMutableData appendData:].

### CODE REVIEW

**Comment by javierag** [comment]
This is built upon #242 . When it is merged, I will rebase and adapt this branch to any changes.

**Comment by blaxter** [comment]
So we are in a loop parsing characters and we make another identical loop with same conditions inside that? I don't think this optimization is worthy tbh. I've done a quick test (parse one of the rtf 5000 times) and I don't see any difference (10.3 seconds with and without this optimization)

**Comment by javierag** [comment]
Yes ,the same conditions are needed to be able to exit when we find control characters.

As for code structure I find clearer that a text section is to be parsed fully in its own block that to fallback to the main loop for each character. Likewise all the control words and its parameters are parsed fully and not character by character.

The optimization is just that the encoding to UTF8 is done once instead that character-by-character and to reduce the number of instance creations. Obviously it will depend on how long is the text section (it equates  roughly is the event description using the characters expected for the 'editor lanugage' setting).

Since I think it also enhances the structure, I would go ahead and merge it.

**Comment by sixstone-qq** [comment]
@javierag, could you provide an example in metrics with the benefits of this optimisation? That is, a long UTF8 RTF file, take into account, that normally, not mine, the email text or event descriptions are not such longer (may it be 25 lines long?)

Thank you for providing this patch :)

**Comment by javierag** [comment]
I have checked myself and I do not saw time differences. Valgrind reports less memory allocs, expected because less objects are created, but it seems that its effects are negligible.

So it seems that the only justification is that I found the flow more logical like that.

**Comment by blaxter** [comment]
while (some_condition) {
        if (a) {
            ...
        } else if (b) {
            ...
        } else if (c) {
            ...
        } else {
            do_something;
        }
    }

    while (some_condition) {
        if (a) {
            ...
        } else if (b) {
            ...
        } else if (c) {
            ...
        } else { 
            while (some_condition) {
                if (a || b || c)
                    break;
                do_something;
            }
        }
    }

I don't see how the second one is better than the first one.

It'd be better though, if you encapsulate the second loop in a `parseTextSection` function or something like that.

**Comment by javierag** [comment]
OK, unless there are more favorable opinions, we close this.

**Comment by sixstone-qq** [comment]
As some developers don't see any benefit and I foresee some early optimisation here, we could close this if you don't mind.

**Pull request closed without merging**
