### PR TITLE
Merge upstream

### PR DESCRIPTION
**Pull request by papajulio**
Testing latest changes from upstream/master and undoing our reverts

### CODE REVIEW

**Comment by papajulio** [comment]
Please @blaxter, @javierag whenever you can please take a look to this, the tests seems to be passing ok, with the known issues in this other PR with trusty merged #151. I will do some more testing manually but I would like you to review it.

**Comment by sixstone-qq** [comment]
He mostly fix EAS server implementation, we should check that part.

**Comment by blaxter** [comment]
:+1: to merge, but careful because when merging to master we have to change `SoObjects/SOGo/SOGoUserManager.m` in lines 815 and 772 `currentUser` -> `theCurrentUser` (it doesn't show up as a conflict)

**Comment by papajulio** [comment]
Yes please @blaxter whenever you can merge it. I will release new package to be tested and prepare a PR for inverse.

**Pull request merged**
