### PR TITLE
Unify user sources API

### PR DESCRIPTION
**Pull request by exekias**
This change unifies user sources API and allows new user sources to be loaded dynamically

### CODE REVIEW

**Comment by exekias** [comment]
Just a note, this branch was reviewed and even tested some time ago, it's the same now, plus my 2 commits :)

**Comment by blaxter** [comment]
[](http://static.gamespot.com/uploads/original/1425/14251903/2519867-8877495172-1082..gif)

**Comment by exekias** [comment]
jenkins retest this please

@ devs just ignore this, I'm testing

**Comment by sixstone-qq** [comment]
@exekias as does Jenkins do?

**Comment by sixstone-qq** [comment]
:+1:

**Pull request merged**
