### PR TITLE
oc-rtf: no color table definition

### PR DESCRIPTION
**Pull request by blaxter**
Be able to parse rtf files without `\colortbl` control word

### CODE REVIEW

**Comment by sixstone-qq** [comment]
Could you pass me the failing RTF doc? Was the `color_index` valid? If so, then I think the RTF document is incomplete or I miss something.

**Comment by blaxter** [comment]
Yeah, probably the rtf was manually generated or not from outlook but why crash if we can avoid it?

https://github.com/Zentyal/sogo/blob/jgarcia/unittest-working/Tests/Unit/Fixtures/zentyal_crash_6977.rtf

**Comment by blaxter** [comment]
test this please

**Comment by blaxter** [comment]
test this please :unamused:

**Comment by sixstone-qq** [comment]
According to RTF Specification version 1.9.1 on Color Table section says:

```
The missing definition indicates that color 0 is the `'auto'' color.
```
So I think we can assume if table colour definition is missing, we can use `auto` colour font instead of continue. In HTML it can be no font label.

I think putting the `continue` before assigning to the `formatting_options` will avoid having an sporious `</font>` tag.

**Comment by sixstone-qq** [comment]
:+1: Much better :)

**Pull request merged**
